# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_7Z "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_INNOSETUP "OFF")
set(CPACK_BINARY_NSIS "ON")
set(CPACK_BINARY_NUGET "OFF")
set(CPACK_BINARY_WIX "OFF")
set(CPACK_BINARY_ZIP "OFF")
set(CPACK_BUILD_SOURCE_DIRS "/home/shash29/vlc/contrib/win32/openjpeg;/home/shash29/vlc/contrib/win32/openjpeg/vlc_build")
set(CPACK_BUNDLE_NAME "OpenJPEG 2.5")
set(CPACK_CMAKE_GENERATOR "Ninja")
set(CPACK_COMPONENTS_ALL "Headers;Libraries;Unspecified")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.31/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "OPENJPEG built using CMake")
set(CPACK_GENERATOR "NSIS")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/shash29/vlc/contrib/win32/openjpeg/vlc_build;OPENJPEG;ALL;/")
set(CPACK_INSTALL_PREFIX "/home/shash29/vlc/contrib/x86_64-w64-mingw32")
set(CPACK_MODULE_PATH "/home/shash29/vlc/contrib/win32/openjpeg/cmake")
set(CPACK_NSIS_DISPLAY_NAME "OpenJPEG 2.5")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
set(CPACK_NSIS_PACKAGE_NAME "OpenJPEG 2.5")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/x86_64-w64-mingw32-objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/x86_64-w64-mingw32-objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/shash29/vlc/contrib/win32/openjpeg/vlc_build/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/home/shash29/vlc/contrib/win32/openjpeg/vlc_build/LICENSE.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "OpenJPEG - OpenJPEG a JPEG 2000 implementation.")
set(CPACK_PACKAGE_FILE_NAME "openjpeg-2.5.4-win32-x86")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "OpenJPEG 2.5")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "OpenJPEG 2.5")
set(CPACK_PACKAGE_NAME "openjp2")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "OpenJPEG Team")
set(CPACK_PACKAGE_VERSION "2.5.4")
set(CPACK_PACKAGE_VERSION_MAJOR "2")
set(CPACK_PACKAGE_VERSION_MINOR "5")
set(CPACK_PACKAGE_VERSION_PATCH "4")
set(CPACK_PRODUCTBUILD_DOMAINS "ON")
set(CPACK_READELF_EXECUTABLE "/usr/bin/x86_64-w64-mingw32-readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/home/shash29/vlc/contrib/win32/openjpeg/vlc_build/LICENSE.txt")
set(CPACK_RESOURCE_FILE_README "/usr/share/cmake-3.31/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-3.31/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "ON")
set(CPACK_SOURCE_GENERATOR "7Z;ZIP")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/shash29/vlc/contrib/win32/openjpeg/vlc_build/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "openjpeg-2.5.4")
set(CPACK_SOURCE_ZIP "ON")
set(CPACK_SYSTEM_NAME "win32-x86")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "win32-x86")
set(CPACK_WIX_INSTALL_SCOPE "perMachine")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/shash29/vlc/contrib/win32/openjpeg/vlc_build/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
